workflows:
  nodejs-workflow:
    name: Node.js Workflow
    environment:
      vars:
        NODE_VERSION: '18' # Use the latest Node.js LTS version
    scripts:
      - name: Set up Node.js
        script: |
          # Install NVM (Node Version Manager)
          curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.3/install.sh | bash
          export NVM_DIR="$HOME/.nvm"
          [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh" # This loads nvm
          [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion" # This loads nvm bash_completion
          
          # Install and use the specified Node.js version
          nvm install $NODE_VERSION
          nvm use $NODE_VERSION
          node -v
          npm -v
      - name: Install dependencies
        script: |
          npm install
          npm install moment-timezone
      - name: Run application
        script: |
          npm start
